[[constraint]]
  name = "github.com/deckarep/golang-set"

[[constraint]]
  name = "github.com/golang/mock"
  version = "1.0.0"

[[constraint]]
  name = "github.com/mattn/go-shellwords"

[[constraint]]
  name = "github.com/mitchellh/go-homedir"

[[constraint]]
  name = "github.com/olekukonko/tablewriter"

[[constraint]]
  name = "github.com/pkg/errors"

[[constraint]]
  name = "github.com/spf13/cobra"

[[constraint]]
  name = "github.com/spf13/pflag"

[[constraint]]
  name = "github.com/spf13/viper"

[[constraint]]
  name = "github.com/tealeg/xlsx"

[[constraint]]
  name = "go.uber.org/zap"

[[constraint]]
  name = "golang.org/x/text"

[[constraint]]
  name = "gopkg.in/cheggaaa/pb.v1"

[[constraint]]
  name = "gopkg.in/resty.v0"

[[constraint]]
  name = "github.com/labstack/echo"

[[constraint]]
  name = "github.com/labstack/gommon"
